# Plausible Analytics — Privacy-friendly Google Analytics alternative
# Usage: /vps template deploy plausible --domain analytics.example.com
version: "3.8"

services:
  plausible:
    image: ghcr.io/plausible/community-edition:v2-latest
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    environment:
      BASE_URL: https://${DOMAIN}
      SECRET_KEY_BASE: ${SECRET_KEY}
      DATABASE_URL: postgres://plausible:${DB_PASSWORD}@postgres:5432/plausible
      CLICKHOUSE_DATABASE_URL: http://clickhouse:8123/plausible
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.plausible.entrypoints=websecure"
      - "traefik.http.routers.plausible.tls.certresolver=letsencrypt"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"
    networks:
      - internal
      - dokploy-network
    depends_on:
      - postgres
      - clickhouse

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: plausible
      POSTGRES_USER: plausible
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: unless-stopped
    volumes:
      - ch_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - internal

volumes:
  pg_data:
  ch_data:

networks:
  internal:
  dokploy-network:
    external: true
